# Generated by Django 5.2.1 on 2025-05-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_livro_categoria_livro_editora'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(blank=True, related_name='livros', to='core.autor'),
        ),
    ]
