# Generated by Django 5.2.1 on 2025-05-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_editora_name_editora_cidade_editora_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editora',
            name='name',
        ),
    ]
